# CI workflow file

name: CI Workflow

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest
    container: python:3.9-slim

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip wheel
            pip install -r requirements.txt.

      - name: Lint with flake8
        run: |
            flake8 app --count --show-source --select=E9,F63,F7,F82 --statistics
            flake8 app --count --max-complexity=10 --max-line-length=127 --statistics
            
      - name: Run unit test with green
        run: green